### ISSUE TITLE
Completely broken when char == signed char

### ISSUE THREAD

**Issue by sesse** [tobiaslocker/base64#2]
Hi,

Encoding seems to be broken on platforms where char is signed; it doesn't round-trip:

```
#include <stdio.h>
#include "base64.h"

int main(int argc, char **argv)
{
	printf("%s\n", base64::to_base64(base64::from_base64(argv[1])).c_str());
}

> ./base64 U5z=    
Upw=
``

Compiling with -funsigned-char seems to fix it.

**Comment by tobiaslocker** [comment]
What's your compiler?

**Comment by sesse** [comment]
The simplest fix is to use for (const unsigned char : data) instead of auto and a reference.

**Comment by guruofquality** [comment]
FYI the `auto num_val = static_cast<unsigned int>(c);` is not really going to cut it on platforms where "naked" char is by default signed (like arm) https://www.arm.linux.org.uk/docs/faqs/signedchar.php

Just as an example  the following code forces char to signed and casts it to an unsigned int. This would totally mess up the `bit_stream += num_val << offset;` logic.

```
#include <stdio.h>

int main(void)
{
    //if char is signed, this prints 0xffffffff
    signed char c = 0xff;
    auto num_val = static_cast<unsigned int>(c);
    printf("0x%x\n", num_val);
    return 0;
}
```

* I think a good fix is to change the loop `(const unsigned char : data)`
* or maybe a mask: `bit_stream += (num_val & 0xff) << offset;`

**Comment by tobiaslocker** [comment]
@guruofquality I tried fixing it with the suggestion from @sesse but it didn't work. A pull request with your fix would be highly appreciated!

**Comment by guruofquality** [comment]
Sorry I had that backwards, on x86 gcc char is signed, but arm is unsigned.

The patch is just like @sesse said:

```
diff --git a/include/base64.hpp b/include/base64.hpp
index 2e8127f..3fe21e0 100644
--- a/include/base64.hpp
+++ b/include/base64.hpp
@@ -19,7 +19,7 @@ inline std::string to_base64(std::string const &data) {
   const std::string base64_chars = get_base64_chars();
   std::string encoded;
   int offset = 0;
-  for (auto const &c : data) {
+  for (unsigned char c : data) {
     auto num_val = static_cast<unsigned int>(c);
     offset = 16 - counter % 3 * 8;
     bit_stream += num_val << offset;
```

I made a little tester with random "binary" data that is a little more aggressive to show the problem. The issue is with the encoder and values that would use the sign bit, so you cant test it with ascii characters on input
```
#include "base64.hpp"
#include <iostream>
#include <type_traits>

using namespace base64;

int main() {

    std::string original;
    for (int i = 0; i < 1024; i++) original += char(std::rand());

    std::cout << "char is " << (std::is_signed<char>::value?"signed":"unsigned") << std::endl;

    auto encoded= to_base64(original);
    auto s = from_base64(encoded);
    if (s == original) std::cout << "PASS!!\n";
    else std::cout << "FAIL!!\n";
    return 0;
}
```
